### ISSUE TITLE
no_std support

### ISSUE THREAD

**Issue by adityashah1212** [dtolnay/paste#52]
Like the title says, could you support `#![no_std]` environment?

**Comment by dtolnay** [comment]
This is already supported.

**Comment by TomzBench** [comment]
@dtolnay seems like regression, `#[no_std]` maybe accidentally removed

**Comment by taiki-e** [comment]
@TomzBench Since this crate is a proc-macro, it works with no-std if the generated code works with no-std even if the crate itself does not have `#![no_std]`. Actually, I use this crate for [code for no-std targets in my project](https://github.com/taiki-e/portable-atomic/blob/67d17294cc8d7e96b07a3f904daee349456a4d90/tests/no-std-qemu/Cargo.toml#L14).

**Comment by TomzBench** [comment]
> @TomzBench Since this crate is a proc-macro, it works with no-std if the generated code works with no-std even if the crate itself does not have `#![no_std]`. Actually, I use this crate for [code for no-std targets in my project](https://github.com/taiki-e/portable-atomic/blob/67d17294cc8d7e96b07a3f904daee349456a4d90/tests/no-std-qemu/Cargo.toml#L14).

yep sorry - one of my other dependencies was pulling in std_lib.

thanks!
